#!/bin/python3

import sys
import os
import argparse

sys.path.append("../adbmodule/")
import adb
from pyscf import scf, gto
import numpy as np
import numpy
import pandas as pd
import datetime
from time import time

from pyscf.lib import logger
from pyscf import lib
from pyscf.scf import chkfile
from pyscf import __config__

TIGHT_GRAD_CONV_TOL = getattr(__config__, 'scf_hf_kernel_tight_grad_conv_tol', True)


def kernel(mf, conv_tol=1e-10, conv_tol_grad=None,
           dump_chk=True, dm0=None, adaptive=False, atol=1e-3,
           callback=None, conv_check=True, **kwargs):
    '''kernel: the SCF driver.

    Args:
        mf : an instance of SCF class
            mf object holds all parameters to control SCF.  One can modify its
            member functions to change the behavior of SCF.  The member
            functions which are called in kernel are

            | mf.get_init_guess
            | mf.get_hcore
            | mf.get_ovlp
            | mf.get_veff
            | mf.get_fock
            | mf.get_grad
            | mf.eig
            | mf.get_occ
            | mf.make_rdm1
            | mf.energy_tot
            | mf.dump_chk

    Kwargs:
        conv_tol : float
            converge threshold.
        conv_tol_grad : float
            gradients converge threshold.
        dump_chk : bool
            Whether to save SCF intermediate results in the checkpoint file
        dm0 : ndarray
            Initial guess density matrix.  If not given (the default), the kernel
            takes the density matrix generated by ``mf.get_init_guess``.
        adaptive : bool
            Whether to use the adaptive solver.  Default is False.
        atol : float
            Tolerance for the adaptive solver.  Default is 1e-3.
        callback : function(envs_dict) => None
            callback function takes one dict as the argument which is
            generated by the builtin function :func:`locals`, so that the
            callback function can access all local variables in the current
            environment.

    Returns:
        A list :   scf_conv, e_tot, mo_energy, mo_coeff, mo_occ

        scf_conv : bool
            True means SCF converged
        e_tot : float
            Hartree-Fock energy of last iteration
        mo_energy : 1D float array
            Orbital energies.  Depending the eig function provided by mf
            object, the orbital energies may NOT be sorted.
        mo_coeff : 2D array
            Orbital coefficients.
        mo_occ : 1D array
            Orbital occupancies.  The occupancies may NOT be sorted from large
            to small.

    Examples:

    >>> from pyscf import gto, scf
    >>> mol = gto.M(atom='H 0 0 0; H 0 0 1.1', basis='cc-pvdz')
    >>> conv, e, mo_e, mo, mo_occ = scf.hf.kernel(scf.hf.SCF(mol), dm0=numpy.eye(mol.nao_nr()))
    >>> print('conv = %s, E(HF) = %.12f' % (conv, e))
    conv = True, E(HF) = -1.081170784378
    '''

    if 'init_dm' in kwargs:
        raise RuntimeError('''
You see this error message because of the API updates in pyscf v0.11.
Keyword argument "init_dm" is replaced by "dm0"''')
    cput0 = (logger.process_clock(), logger.perf_counter())
    if conv_tol_grad is None:
        conv_tol_grad = numpy.sqrt(conv_tol)
        logger.info(mf, 'Set gradient conv threshold to %g', conv_tol_grad)

    mol = mf.mol
    if dm0 is None:
        dm = mf.get_init_guess(mol, mf.init_guess)
    else:
        dm = dm0

    h1e = mf.get_hcore(mol)
    vhf = mf.get_veff(mol, dm)
    e_tot = mf.energy_tot(dm, h1e, vhf)
    logger.info(mf, 'init E= %.15g', e_tot)

    scf_conv = False
    mo_energy = mo_coeff = mo_occ = None

    s1e = mf.get_ovlp(mol)
    cond = lib.cond(s1e)
    logger.debug(mf, 'cond(S) = %s', cond)
    if numpy.max(cond)*1e-17 > conv_tol:
        logger.warn(mf, 'Singularity detected in overlap matrix (condition number = %4.3g). '
                    'SCF may be inaccurate and hard to converge.', numpy.max(cond))

    # Skip SCF iterations. Compute only the total energy of the initial density
    if mf.max_cycle <= 0:
        fock = mf.get_fock(h1e, s1e, vhf, dm)  # = h1e + vhf, no DIIS
        mo_energy, mo_coeff = mf.eig(fock, s1e)
        mo_occ = mf.get_occ(mo_energy, mo_coeff)
        return scf_conv, e_tot, mo_energy, mo_coeff, mo_occ

    if isinstance(mf.diis, lib.diis.DIIS):
        mf_diis = mf.diis
    elif mf.diis:
        assert issubclass(mf.DIIS, lib.diis.DIIS)
        mf_diis = mf.DIIS(mf, mf.diis_file)
        mf_diis.space = mf.diis_space
        mf_diis.rollback = mf.diis_space_rollback

        # We get the used orthonormalized AO basis from any old eigendecomposition.
        # Since the ingredients for the Fock matrix has already been built, we can
        # just go ahead and use it to determine the orthonormal basis vectors.
        fock = mf.get_fock(h1e, s1e, vhf, dm)
        _, mf_diis.Corth = mf.eig(fock, s1e)
    else:
        mf_diis = None

    if dump_chk and mf.chkfile:
        # Explicit overwrite the mol object in chkfile
        # Note in pbc.scf, mf.mol == mf.cell, cell is saved under key "mol"
        chkfile.save_mol(mol, mf.chkfile)

    # A preprocessing hook before the SCF iteration
    mf.pre_kernel(locals())

    if adaptive:
        # logger.info(mf, '\nUsing adaptive solver by Huhtasalo\n')
        pass
        
        

    # logger.info(mf, 'init E= %.15g', e_tot)
    print(f'cycle= 0 E= {e_tot:.15g}')
    cput1 = logger.timer(mf, 'initialize scf', *cput0)
    for cycle in range(mf.max_cycle):
        dm_last = dm
        last_hf_e = e_tot

        fock = mf.get_fock(h1e, s1e, vhf, dm, cycle, mf_diis)
        mo_energy, mo_coeff = mf.eig(fock, s1e)
        mo_occ = mf.get_occ(mo_energy, mo_coeff)
        dm = mf.make_rdm1(mo_coeff, mo_occ)
        vhf = mf.get_veff(mol, dm, dm_last, vhf)
        e_tot = mf.energy_tot(dm, h1e, vhf)

        # Here Fock matrix is h1e + vhf, without DIIS.  Calling get_fock
        # instead of the statement "fock = h1e + vhf" because Fock matrix may
        # be modified in some methods.
        fock = mf.get_fock(h1e, s1e, vhf, dm)  # = h1e + vhf, no DIIS
        norm_gorb = numpy.linalg.norm(mf.get_grad(mo_coeff, mo_occ, fock))
        if not TIGHT_GRAD_CONV_TOL:
            norm_gorb = norm_gorb / numpy.sqrt(norm_gorb.size)
        norm_ddm = numpy.linalg.norm(dm-dm_last)
        logger.info(mf, 'cycle= %d E= %.15g  delta_E= %4.3g  |g|= %4.3g  |ddm|= %4.3g',
                    cycle+1, e_tot, e_tot-last_hf_e, norm_gorb, norm_ddm)
        print(f'cycle= {cycle+1:d} E= {e_tot:19.15g}  delta_E= {e_tot-last_hf_e:4.3g}  |g|= {norm_gorb:4.3g}  |ddm|= {norm_ddm:4.3g}')

        if callable(mf.check_convergence):
            scf_conv = mf.check_convergence(locals())
        elif abs(e_tot-last_hf_e) < conv_tol and norm_gorb < conv_tol_grad:
            scf_conv = True

        if dump_chk:
            mf.dump_chk(locals())

        if callable(callback):
            callback(locals())

        cput1 = logger.timer(mf, 'cycle= %d'%(cycle+1), *cput1)

        if scf_conv:
            break
    print()

    if scf_conv and conv_check:
        # An extra diagonalization, to remove level shift
        #fock = mf.get_fock(h1e, s1e, vhf, dm)  # = h1e + vhf
        mo_energy, mo_coeff = mf.eig(fock, s1e)
        mo_occ = mf.get_occ(mo_energy, mo_coeff)
        dm, dm_last = mf.make_rdm1(mo_coeff, mo_occ), dm
        vhf = mf.get_veff(mol, dm, dm_last, vhf)
        e_tot, last_hf_e = mf.energy_tot(dm, h1e, vhf), e_tot

        fock = mf.get_fock(h1e, s1e, vhf, dm)
        norm_gorb = numpy.linalg.norm(mf.get_grad(mo_coeff, mo_occ, fock))
        if not TIGHT_GRAD_CONV_TOL:
            norm_gorb = norm_gorb / numpy.sqrt(norm_gorb.size)
        norm_ddm = numpy.linalg.norm(dm-dm_last)

        conv_tol = conv_tol * 10
        conv_tol_grad = conv_tol_grad * 3
        if callable(mf.check_convergence):
            scf_conv = mf.check_convergence(locals())
        elif abs(e_tot-last_hf_e) < conv_tol or norm_gorb < conv_tol_grad:
            scf_conv = True
        logger.info(mf, 'Extra cycle  E= %.15g  delta_E= %4.3g  |g|= %4.3g  |ddm|= %4.3g',
                    e_tot, e_tot-last_hf_e, norm_gorb, norm_ddm)
        if dump_chk:
            mf.dump_chk(locals())

    if mf.disp is not None:
        e_disp = mf.get_dispersion()
        mf.scf_summary['dispersion'] = e_disp
        e_tot += e_disp

    logger.timer(mf, 'scf_cycle', *cput0)
    # A post-processing hook before return
    mf.post_kernel(locals())
    return scf_conv, e_tot, mo_energy, mo_coeff, mo_occ

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Run adaptive basis Hartree-Fock calculation."
    )
    parser.add_argument(
        "-m", "--mpath", type=str, required=True, help="path to molecule .xyz file"
    )
    parser.add_argument(
        "-b", "--basis", type=str, required=True, help="basis set"
    )
    parser.add_argument(
        "-c", "--cutoff", type=float, required=False, default=None,
        help="mask cutoff percentage for ABS, must be between [0.0, 1.0]"
    )
    
    args = parser.parse_args()

    molpath = args.mpath
    basis = args.basis
    cutoff = args.cutoff
    if cutoff is not None and (cutoff < 0.0 or cutoff > 1.0):
        raise argparse.ArgumentTypeError('Value has to be between 0 and 1')

    spin = charge = None

    if 'spin' in molpath:
        spin = molpath.split('/')[-1].split('.')
        spin = list(filter(lambda x: 'spin' in x, spin))[0]
        spin = int(spin[-1])
    if 'charge' in molpath:
        charge = molpath.split('/')[-1].split('.')
        charge = list(filter(lambda x: 'charge' in x, charge))[0]
        charge = int(charge[-1])
    mol = gto.M(
        atom = molpath,
        basis = basis,
        verbose = 0,
        spin=spin,
        charge=charge
    )

    mol.verbose = 0
    mf = scf.HF(mol)
    start = time()
    dm0 = mf.get_init_guess(key='atom')
    end = time()
    t_dm0 = end - start
    start = time()
    F = mf.get_fock(dm=dm0)
    end = time()
    t_F = end - start

    mf.init_guess = 'atom'
    mf.sap_basis = 'sapgrasplarge'
    S = mf.get_ovlp()

    start = time()
    smask = adb.find_subspace(
        F, S, mol, mf,
        conv_tol=1e-3, get_smask=True, dm0=dm0,
        verbose=False, variant='enocc',
        mask_cutoff=cutoff,
    )
    end = time()
    mask = adb.smask_to_mask(smask, mol.cart)
    t_find_subspace = end - start

    start = time()
    mf.scf_conv, mf.e_tot, mf.mo_energy, mf.mo_coeff, mf.mo_occ = kernel(mf)
    end = time()
    t_fullHF = end - start
    Efull = mf.e_tot

    submol = adb.create_shell_separated_mol(mol)
    submol._bas = submol._bas[[sm[0] for sm in smask]]
    submf = scf.HF(submol)
    submf.init_guess = 'atom'

    start = time()
    submf.kernel(dm0=dm0[:, mask][mask, :])
    subdm = submf.make_rdm1()
    end = time()
    t_subHF = end - start
    esub = submf.e_tot

    mol.verbose = 0
    mf = scf.HF(mol)
    dm0 = np.zeros_like(dm0)
    idx = np.where(mask)[0]
    for j,i in enumerate(idx):
        dm0[i][idx] = subdm[j]

    # mf.max_cycle = 0
    start = time()
    # mf.kernel(dm  0=dm0)
    mf.scf_conv, mf.e_tot, mf.mo_energy, mf.mo_coeff, mf.mo_occ = kernel(mf, dm0=dm0)
    end = time()
    Esubinit = mf.e_tot
    t_subinit = end -start

    print('\n\n')
    print(f't_dm0: {t_dm0:.3f}')
    print(f't_F: {t_F:.3f}')
    print(f't_find_subspace: {t_find_subspace:.3f}')
    print('Number of shells in subspace:  ', np.count_nonzero([m[0] for m in smask]))
    print('Number of shells in full space:', len(smask))
    print(f't_fullHF: {t_fullHF:.3f}')
    print(f't_subHF: {t_subHF:.3f}')
    print(f't_subinitHF: {t_subinit:.3f}')

    print(f'ABS: {(t_dm0 + t_dm0 + t_F + t_find_subspace + t_subHF + t_subinit):.3f}')
    print(f'E_full: {Efull:.8f}')
    print(f'E_sub: {esub:.8f}')